name = "edu-connect"
type = "javascript"

account_id = "3a7f9832e5ec8abbc1770dad0d2d96c1"
workers_dev = true  # Garde true si tu veux utiliser workers.dev
compatibility_date = "2024-02-10"

[build]
command = "npm install && npm run build"
upload.format = "modules"  # Remplace "service-worker" par "modules" pour éviter les erreurs
upload.dir = "dist"  # Assure-toi que la sortie de ton build est bien dans ce dossier

[env.production]
name = "edu-connect-prod"
route = "edu-connect.narcissedesire5.workers.dev"  # Supprime si workers_dev reste activé
zone_id = ""  # Remplis si tu as un domaine personnalisé (sinon retire)
